using Microsoft.Extensions.Options;
using RestSharp;
using WarrantyBee.Application.Abstractions.Services;
using WarrantyBee.Application.Configuration;

namespace WarrantyBee.Infrastructure.Services;

/// <summary>
/// Implementation of reCAPTCHA Enterprise/v3 verification service.
/// </summary>
public class ReCaptchaService : ICaptchaService
{
    private readonly ReCaptchaConfiguration? _config;
    private readonly RestClient _client;
    private readonly bool _isEnabled;

    /// <summary>
    /// Initializes a new instance of the <see cref="ReCaptchaService"/> class.
    /// </summary>
    /// <param name="config">The application configuration containing reCAPTCHA settings.</param>
    public ReCaptchaService(IOptions<AppConfiguration> config)
    {
        _isEnabled = config.Value.IsCaptchaEnabled;
        _config = config.Value.ReCaptcha;
        _client = new RestClient("https://www.google.com/recaptcha/api/siteverify");
    }

    /// <summary>
    /// Validates the reCAPTCHA token by calling the Google verification API.
    /// </summary>
    /// <param name="captchaResponse">The token generated by the client-side reCAPTCHA.</param>
    /// <returns>True if the token is valid and meets the minimum score requirement; otherwise, false.</returns>
    public async Task<bool> ValidateAsync(string captchaResponse)
    {
        if (!_isEnabled) return true;
        if (_config == null || string.IsNullOrWhiteSpace(_config.Secret)) return false;

        var request = new RestRequest("/", Method.Post);
        request.AddParameter("secret", _config.Secret);
        request.AddParameter("response", captchaResponse);

        try
        {
            var response = await _client.ExecuteAsync<ReCaptchaResponse>(request);
            if (response.IsSuccessful && response.Data != null)
            {
                // For v3/Enterprise, we check the success flag and potentially the score
                return response.Data.Success && response.Data.Score >= _config.MinimumScore;
            }
        }
        catch
        {
            // Log error via telemetry if needed
        }

        return false;
    }

    private class ReCaptchaResponse
    {
        public bool Success { get; set; }
        public double Score { get; set; }
        public string? Action { get; set; }
    }
}
